# Generated by Django 6.1 on 2026-08-17 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_team_teammembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(through='users.TeamMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
