# Generated by Django 6.1 on 2026-08-20 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_team_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.RemoveConstraint(
            model_name='teammembership',
            name='unique_user_in_team',
        ),
        migrations.RemoveField(
            model_name='teammembership',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teammembership',
            name='user',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamMembership',
        ),
    ]
